apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assignment-api-hpa
  namespace: k8s-demo
  labels:
    app: assignment-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assignment-api
  minReplicas: 4
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
