apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: k8s-demo
  labels:
    app: assignment-api
data:
  DB_HOST: postgres-service.k8s-demo.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD_FILE: /secrets/db-password
