apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: k8s-demo
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
